version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieDB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_net

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/movieDB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkey
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: sh -c "npx prisma db push && npm start"
    networks:
      - app_net

  worker:
    build: .
    command: node src/workers/notificationWorker.js
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  pg_data:
